<a href="https://colab.research.google.com/github/Abhilash9432/Python-Notebooks/blob/main/Numpy/Numpy_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
a = [1,2,3,4,5]
res = [i**2 for i in a]
print(res)
print(type(a))

[1, 4, 9, 16, 25]
<class 'list'>


In [4]:
b=np.array(a)
print(b)
print(type(b))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [6]:
#Numpy Oprations
print(b**2) #loop not required to do element level operation
print(b*2)
print(b-2)
print(b+2)
print(b%2)

[ 1  4  9 16 25]
[ 2  4  6  8 10]
[-1  0  1  2  3]
[3 4 5 6 7]
[1 0 1 0 1]


In [7]:
veryBigRange = range(10000000)
python_list = list(veryBigRange)
np_array = np.array(veryBigRange)

In [8]:
%timeit [i**2 for i in python_list]

3.46 s ± 559 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [9]:
%timeit np_array**2

25.9 ms ± 529 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [12]:
a=[1,2,3,4,5]
print(type(a))
print(a[1])
print(a[-2])
print(a[1:4])

<class 'list'>
2
4
[2, 3, 4]


In [11]:
b = np.array([1,2,3,4,5])
print(type(b))
print(b[1])
print(b[-2])
print(b[1:4])

<class 'numpy.ndarray'>
2
4
[2 3 4]


In [13]:
arr = np.array([1,2,3,4,5,6,7])
print(arr)
print(type(arr)) # what is the type of the variable
print(len(arr)) # what is the len, same as len in python list
print(arr.ndim) # total num of dimensions
print(arr.shape) # what is the shape, like rows and columns
print(arr.size) # total num of elements
print(arr.dtype) # what data type will it store

[1 2 3 4 5 6 7]
<class 'numpy.ndarray'>
7
1
(7,)
7
int64


In [14]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(arr)
print(type(arr)) # what is the type of the variable
print(len(arr)) # what is the len, same as len in python list
print(arr.ndim) # total num of dimensions
print(arr.shape) # what is the shape, like rows and columns
print(arr.size) # total num of elements
print(arr.dtype) # what data type will it store

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
<class 'numpy.ndarray'>
4
2
(4, 3)
12
int64


In [3]:
arr= np.array([1.2,3.7,2.3,5.8,8.3,7.2])
print(arr)
print(type(arr)) # what is the type of the variable
print(len(arr)) # what is the len, same as len in python list
print(arr.ndim) # total num of dimensions
print(arr.shape) # what is the shape, like rows and columns
print(arr.size) # total num of elements
print(arr.dtype) # what data type will it store


[1.2 3.7 2.3 5.8 8.3 7.2]
<class 'numpy.ndarray'>
6
1
(6,)
6
float64


In [6]:
print(list(range(5)))
print(list(range(2,5)))
print(list(range(2,10,2)))

[0, 1, 2, 3, 4]
[2, 3, 4]
[2, 4, 6, 8]


In [7]:
#start,end,step should be int
print(list(range(1,10,2.5)))

TypeError: 'float' object cannot be interpreted as an integer

In [11]:
print(np.arange(5))
print(np.arange(1,4))
print(np.arange(2,10,2))
print(np.arange(2,10,1.5)) #start,end,step can be int/float

[0 1 2 3 4]
[1 2 3]
[2 4 6 8]
[2.  3.5 5.  6.5 8.  9.5]


In [14]:
#linspace to get linearly spaced numbers, need to give start, end and no of samples required
arr = np.linspace(2,10,8)
print(arr)
print(arr[1]-arr[0])
print(arr[2]-arr[1])
print(arr[3]-arr[2])

[ 2.          3.14285714  4.28571429  5.42857143  6.57142857  7.71428571
  8.85714286 10.        ]
1.1428571428571428
1.1428571428571428
1.1428571428571432


In [15]:
lst = [1,2,3,4,5]
print(lst)
arr = np.array(lst)
print(arr)
print(arr.dtype)

[1, 2, 3, 4, 5]
[1 2 3 4 5]
int64


In [16]:
lst = [1,2,3,4,5.2]
print(lst)
arr = np.array(lst)
print(arr)
print(arr.dtype)

[1, 2, 3, 4, 5.2]
[1.  2.  3.  4.  5.2]
float64


In [18]:
lst = [1,2,'cat',4,5]
print(lst)
arr = np.array(lst)
print(arr)
print(arr.dtype)

[1, 2, 'cat', 4, 5]
['1' '2' 'cat' '4' '5']
<U21


In [20]:
lst = [1,2,3,4,5]
print(lst)
arr = np.array(lst,dtype = float)
print(arr)
print(arr.dtype)

[1, 2, 3, 4, 5]
[1. 2. 3. 4. 5.]
float64


In [22]:
#astype function >> type casting
lst = [1,2,3,4,5]
print(lst)
arr = np.array(lst)
print(arr)
print(arr.dtype)
arr = arr.astype(float)
print(arr)
print(arr.dtype)

[1, 2, 3, 4, 5]
[1 2 3 4 5]
int64
[1. 2. 3. 4. 5.]
float64


In [23]:
arr=np.array([10,20,30,40,50,-40,-30,-20,-10])
print(arr)

[ 10  20  30  40  50 -40 -30 -20 -10]


In [24]:
print(arr[1])
print(arr[-2])
print(arr[1:7])

20
-20
[ 20  30  40  50 -40 -30]


In [26]:
print(arr[1],arr[3],arr[0],arr[-1])
print(arr[[1,3,0,-1]]) #need to use double bracket [[]] else will get error like in next snippet

20 40 10 -10
[ 20  40  10 -10]


In [28]:
print(arr[1,3,0,1])

IndexError: too many indices for array: array is 1-dimensional, but 4 were indexed

In [29]:
# fancy indexing
arr = np.array([0,10,20,30,40,50,-40,-30,-20,-10])
print(arr)


[  0  10  20  30  40  50 -40 -30 -20 -10]


In [30]:
arr>20

array([False, False, False,  True,  True,  True, False, False, False,
       False])

In [31]:
arr[[False, False, False,  True,  True,  True, False, False, False,
       False]]

array([30, 40, 50])

In [32]:
arr[arr>20]

array([30, 40, 50])

In [34]:
arr = np.arange(1,10)
print(arr)
print("Even Numbers: ",arr[arr%2==0])
print("Odd Numbers: ",arr[arr%2==1])

[1 2 3 4 5 6 7 8 9]
Even Numbers:  [2 4 6 8]
Odd Numbers:  [1 3 5 7 9]


In [37]:
file_loc = 'https://gist.github.com/singhsidhukuldeep/8190b6dbb2d6d7f8acc6110e2d60c9d2/raw/7a9db1f2241f7df1ec4ce31ffa4a1c2bc4144e83/survey.txt'
score = np.loadtxt(file_loc, dtype = 'int')
print(score)
print(type(score))
print(score.dtype)
print(score.size)
print(score.shape)

[ 7 10  5 ...  5  9 10]
<class 'numpy.ndarray'>
int64
1167
(1167,)


In [42]:

# 9-10>> promoters
# 7-8 >> netutral users/passive
# 0-6 >> detractors

promoters = score[score>=9]
print(promoters[:5])
num_promoters = len(promoters)
print(num_promoters)
percent_promoters = (num_promoters/len(score))*100
print(percent_promoters)

[10  9  9  9  9]
609
52.185089974293064


In [43]:
detractors = score[score<=6]
print(detractors[:5])
num_detractors = len(detractors)
print(num_detractors)
percent_detractors = (num_detractors/len(score))*100
print(percent_detractors)

[5 4 4 5 1]
332
28.449014567266495


In [45]:
#NET PROMOTER SCORE
NPS = percent_promoters-percent_detractors
print(NPS)
print(round(NPS,2))

23.73607540702657
23.74
